backend:
  name: git-gateway
  repo: Nathan-0001/Keystone
  branch: main
  identity_url: https://auth.decapbridge.com/sites/7d78ad21-fed2-4874-8940-b7b5cc0c8759
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

logo_url: https://decapbridge.com/decapcms-with-bridge.svg

site_url: https://keystone-archaeology.netlify.app

media_folder: "assets/IMG"
public_folder: "assets/IMG"

collections:
  - name: "work"
    label: "Current Work"
    files:
      - file: "data/current-work.json"
        label: "Projects"
        name: "projects"
        format: "json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            allow_add: true
            collapsed: false
            fields:
              - { label: "Location", name: "location", widget: "string", required: true }
              - { label: "Subheading", name: "subheading", widget: "string", required: false }
              - { label: "Start Date", name: "startDate", widget: "string", required: false }
              - { label: "End Date", name: "endDate", widget: "string", required: false }
              - { label: "Photo", name: "photo", widget: "image", required: false }
              - { label: "Google Maps Link", name: "mapLink", widget: "string", required: false }
              - { label: "Description", name: "description", widget: "text", required: false }
